"""changed Column to booleane

Revision ID: 2c44bea894f9
Revises: 9f9944d2d1bc
Create Date: 2023-08-07 15:16:30.216615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c44bea894f9'
down_revision = '9f9944d2d1bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
